version: '3.8'
services:
  simple-linkz:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    environment:
      - PORT=3000
      - SESSION_SECRET=${SESSION_SECRET:-}
    restart: unless-stopped
